### ISSUE TITLE
Question on code coverage

### ISSUE THREAD

**Issue by sarthak-kapoor25** [ayltai/Newspaper#133]
Hi ,

There is one doubt i am trying to generate code coverage using Jacoco but not getting it.
Please see the output of my CircleCI
![circle](https://user-images.githubusercontent.com/36633421/48834711-76e5ef00-eda4-11e8-9df4-1703f2f25d82.png)

PFA the config.yml file 

![jacoco](https://user-images.githubusercontent.com/36633421/48834915-e8be3880-eda4-11e8-8030-91ae3a77adff.png)
build.gradle:-

[build_gradle.txt](https://github.com/ayltai/Newspaper/files/2604093/build_gradle.txt)

**Comment by ayltai** [comment]
Question: Does it work if you run it on your computer instead of CircleCI?

It is usually hard to know what went wrong if JaCoCo doesn't generate any error message. I suggest to check if the following folders contain any generated files after you run `jacocoTestReport`:
- `build/intermediates/classes/debug`
- `app/build/reports`

Also, are the paths specified in `coverageSourceDirs` in `build.gradle` correct?
- one is `app/src/main/java`
- but another one is `src/debug/java`
